# subdir-ccflags-y wird an alle Sub-Submodule vererbt.
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_res_mgr
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor_utils
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_cci
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor_io
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_csiphy
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_actuator
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_flash
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_eeprom
subdir-ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_ois

obj-$(CONFIG_SPECTRA_CAMERA) += cam_res_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_utils/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_cci/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_io/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_csiphy/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_actuator/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_flash/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_eeprom/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_ois/
