# Alle Submodul-Verzeichnisse in den Include-Pfad (GCC 13 sucht
# bei #include \"...\" zuerst das Header-, nicht das .c-Verzeichnis)
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_res_mgr
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor_utils
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_cci
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor_io
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_csiphy
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_actuator
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_sensor
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_flash
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_eeprom
ccflags-y += -Idrivers/media/platform/msm/camera_v3/cam_sensor_module/cam_ois

obj-$(CONFIG_SPECTRA_CAMERA) += cam_res_mgr/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_utils/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_cci/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor_io/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_csiphy/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_actuator/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_sensor/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_flash/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_eeprom/
obj-$(CONFIG_SPECTRA_CAMERA) += cam_ois/
