#ifndef _UAPI_LINUX_KSU_FEATURE_H
#define _UAPI_LINUX_KSU_FEATURE_H

#define KSU_FEATURE_VERSION 1

#define KSU_FEATURE_KERNEL_UMOUNT 0
#define KSU_FEATURE_SULOG 1
#define KSU_FEATURE_ADB_ROOT 2
#define KSU_FEATURE_SU_COMPAT 3
#define KSU_FEATURE_AVC_SPOOF 4

#define KSU_FEATURE_MAX 5

#endif
