#ifndef _UAPI_LINUX_KSU_SELINUX_H
#define _UAPI_LINUX_KSU_SELINUX_H

#define KSU_SEPOLICY_CMD_NORMAL_PERM    0
#define KSU_SEPOLICY_CMD_XPERM          1
#define KSU_SEPOLICY_CMD_TYPE_STATE     2
#define KSU_SEPOLICY_CMD_TYPE           3
#define KSU_SEPOLICY_CMD_TYPE_ATTR      4
#define KSU_SEPOLICY_CMD_ATTR           5
#define KSU_SEPOLICY_CMD_TYPE_TRANSITION 6
#define KSU_SEPOLICY_CMD_TYPE_CHANGE    7
#define KSU_SEPOLICY_CMD_GENFSCON       8

#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_ALLOW      0
#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DENY       1
#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_AUDITALLOW 2
#define KSU_SEPOLICY_SUBCMD_NORMAL_PERM_DONTAUDIT  3

#define KSU_SEPOLICY_SUBCMD_XPERM_ALLOW      0
#define KSU_SEPOLICY_SUBCMD_XPERM_AUDITALLOW 1
#define KSU_SEPOLICY_SUBCMD_XPERM_DONTAUDIT  2

#define KSU_SEPOLICY_SUBCMD_TYPE_STATE_PERMISSIVE 0
#define KSU_SEPOLICY_SUBCMD_TYPE_STATE_ENFORCE   1

#define KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_CHANGE 0
#define KSU_SEPOLICY_SUBCMD_TYPE_CHANGE_MEMBER 1

#endif
